DROP TABLE IF EXISTS nomad;

CREATE TABLE nomad (
    ok VARCHAR(4) ,
    updated_epoch INT,
    updated_time VARCHAR(25) ,
    updated_cache VARCHAR(5) ,
    type VARCHAR(6) ,
    result_info_city_name VARCHAR(21) ,
    result_info_city_url VARCHAR(35) ,
    result_info_city_slug VARCHAR(34) ,
    result_info_country_name VARCHAR(20) ,
    result_info_country_url VARCHAR(29) ,
    result_info_country_slug VARCHAR(20) ,
    result_info_region_name VARCHAR(13) ,
    result_info_region_url VARCHAR(21) ,
    result_info_region_slug VARCHAR(13) ,
    result_info_internet_speed_download INT,
    result_info_weather_type VARCHAR(23) ,
    result_info_weather_humidity_label VARCHAR(11) ,
    result_info_weather_humidity_value NUMERIC(3, 2),
    result_info_weather_temperature_celsius INT,
    result_info_weather_temperature_fahrenheit INT,
    result_info_location_latitude NUMERIC(9, 7),
    result_info_location_longitude NUMERIC(10, 7),
    result_info_monthsToVisit INT,
    result_people_checkins INT,
    result_scores_nomadScore NUMERIC(3, 2),
    result_scores_nomad_score NUMERIC(3, 2),
    result_scores_life_score NUMERIC(3, 2),
    result_scores_free_wifi_available NUMERIC(3, 2),
    result_scores_peace_score NUMERIC(2, 1),
    result_scores_fragile_states_index NUMERIC(4, 1),
    result_scores_freedom_score NUMERIC(2, 1),
    result_scores_press_freedom_index NUMERIC(4, 2),
    result_scores_nightlife NUMERIC(3, 2),
    result_scores_leisure NUMERIC(3, 2),
    result_scores_places_to_work NUMERIC(3, 2),
    result_scores_aircon NUMERIC(3, 2),
    result_scores_safety NUMERIC(3, 2),
    result_scores_friendly_to_foreigners NUMERIC(3, 2),
    result_scores_racism NUMERIC(16, 15),
    result_scores_lgbt_friendly NUMERIC(3, 2),
    result_scores_female_friendly NUMERIC(3, 2),
    result_media_image_250 VARCHAR(63) ,
    result_media_image_500 VARCHAR(63) ,
    result_media_image_1000 VARCHAR(64) ,
    result_media_image_1500 VARCHAR(64) ,
    result_cost_local_USD INT,
    result_cost_local_HUF INT,
    result_cost_nomad_USD INT,
    result_cost_nomad_HUF INT,
    result_cost_expat_USD INT,
    result_cost_expat_HUF INT,
    result_cost_longTerm_USD INT,
    result_cost_longTerm_HUF INT,
    result_cost_shortTerm_USD INT,
    result_cost_shortTerm_HUF INT,
    result_cost_hotel_HUF INT,
    result_cost_hotel_USD INT,
    result_cost_airbnb_median_USD INT,
    result_cost_airbnb_median_HUF INT,
    result_cost_airbnb_vs_apartment_price_ratio NUMERIC(14, 12),
    result_cost_non_alcoholic_drink_in_cafe_HUF NUMERIC(5, 2),
    result_cost_non_alcoholic_drink_in_cafe_USD NUMERIC(3, 2),
    result_cost_beer_in_cafe_HUF INT,
    result_cost_beer_in_cafe_USD NUMERIC(4, 2),
    result_cost_coffee_in_cafe_HUF NUMERIC(5, 2),
    result_cost_coffee_in_cafe_USD NUMERIC(4, 2),
    result_cost_coworking_monthly_HUF INT,
    result_cost_coworking_monthly_USD NUMERIC(6, 2),
    result_cost_exchange_rate_USD NUMERIC(16, 15),
    result_tags VARCHAR(20) ,
    result_cost_local_THB INT,
    result_cost_nomad_THB INT,
    result_cost_expat_THB INT,
    result_cost_longTerm_THB INT,
    result_cost_shortTerm_THB INT,
    result_cost_hotel_THB INT,
    result_cost_airbnb_median_THB INT,
    result_cost_non_alcoholic_drink_in_cafe_THB NUMERIC(4, 2),
    result_cost_beer_in_cafe_THB INT,
    result_cost_coffee_in_cafe_THB NUMERIC(4, 2),
    result_cost_coworking_monthly_THB NUMERIC(7, 2),
    result_cost_local_TWD INT,
    result_cost_nomad_TWD INT,
    result_cost_expat_TWD INT,
    result_cost_longTerm_TWD INT,
    result_cost_shortTerm_TWD INT,
    result_cost_hotel_TWD INT,
    result_cost_airbnb_median_TWD INT,
    result_cost_non_alcoholic_drink_in_cafe_TWD NUMERIC(4, 2),
    result_cost_beer_in_cafe_TWD INT,
    result_cost_coffee_in_cafe_TWD NUMERIC(4, 2),
    result_cost_coworking_monthly_TWD NUMERIC(6, 2),
    result_cost_local_CZK INT,
    result_cost_nomad_CZK INT,
    result_cost_expat_CZK INT,
    result_cost_longTerm_CZK INT,
    result_cost_shortTerm_CZK INT,
    result_cost_hotel_CZK INT,
    result_cost_airbnb_median_CZK INT,
    result_cost_non_alcoholic_drink_in_cafe_CZK NUMERIC(12, 10),
    result_cost_beer_in_cafe_CZK NUMERIC(3, 1),
    result_cost_coffee_in_cafe_CZK NUMERIC(4, 2),
    result_cost_coworking_monthly_CZK INT,
    result_cost_local_EUR INT,
    result_cost_nomad_EUR INT,
    result_cost_expat_EUR INT,
    result_cost_longTerm_EUR INT,
    result_cost_shortTerm_EUR INT,
    result_cost_hotel_EUR INT,
    result_cost_airbnb_median_EUR INT,
    result_cost_non_alcoholic_drink_in_cafe_EUR NUMERIC(3, 2),
    result_cost_beer_in_cafe_EUR NUMERIC(12, 11),
    result_cost_coffee_in_cafe_EUR NUMERIC(12, 11),
    result_cost_coworking_monthly_EUR NUMERIC(6, 2),
    result_cost_local_IDR INT,
    result_cost_nomad_IDR INT,
    result_cost_expat_IDR INT,
    result_cost_longTerm_IDR INT,
    result_cost_shortTerm_IDR INT,
    result_cost_hotel_IDR INT,
    result_cost_airbnb_median_IDR INT,
    result_cost_non_alcoholic_drink_in_cafe_IDR NUMERIC(6, 2),
    result_cost_beer_in_cafe_IDR NUMERIC(7, 2),
    result_cost_coffee_in_cafe_IDR NUMERIC(7, 2),
    result_cost_coworking_monthly_IDR NUMERIC(9, 2),
    result_cost_local_VND INT,
    result_cost_nomad_VND INT,
    result_cost_expat_VND INT,
    result_cost_longTerm_VND INT,
    result_cost_shortTerm_VND INT,
    result_cost_hotel_VND INT,
    result_cost_airbnb_median_VND INT,
    result_cost_non_alcoholic_drink_in_cafe_VND NUMERIC(7, 2),
    result_cost_beer_in_cafe_VND NUMERIC(7, 2),
    result_cost_coffee_in_cafe_VND NUMERIC(7, 2),
    result_cost_coworking_monthly_VND INT,
    result_cost_local_NZD INT,
    result_cost_nomad_NZD INT,
    result_cost_expat_NZD INT,
    result_cost_longTerm_NZD INT,
    result_cost_shortTerm_NZD INT,
    result_cost_hotel_NZD INT,
    result_cost_airbnb_median_NZD INT,
    result_cost_non_alcoholic_drink_in_cafe_NZD NUMERIC(3, 2),
    result_cost_beer_in_cafe_NZD NUMERIC(3, 1),
    result_cost_coffee_in_cafe_NZD NUMERIC(3, 2),
    result_cost_coworking_monthly_NZD INT,
    result_cost_local_SEK INT,
    result_cost_nomad_SEK INT,
    result_cost_expat_SEK INT,
    result_cost_longTerm_SEK INT,
    result_cost_shortTerm_SEK INT,
    result_cost_hotel_SEK INT,
    result_cost_airbnb_median_SEK INT,
    result_cost_non_alcoholic_drink_in_cafe_SEK NUMERIC(4, 2),
    result_cost_beer_in_cafe_SEK NUMERIC(4, 2),
    result_cost_coffee_in_cafe_SEK NUMERIC(4, 2),
    result_cost_coworking_monthly_SEK NUMERIC(6, 2),
    result_cost_local_AUD INT,
    result_cost_nomad_AUD INT,
    result_cost_expat_AUD INT,
    result_cost_longTerm_AUD INT,
    result_cost_shortTerm_AUD INT,
    result_cost_hotel_AUD INT,
    result_cost_airbnb_median_AUD INT,
    result_cost_non_alcoholic_drink_in_cafe_AUD NUMERIC(3, 2),
    result_cost_beer_in_cafe_AUD NUMERIC(3, 1),
    result_cost_coffee_in_cafe_AUD NUMERIC(3, 2),
    result_cost_coworking_monthly_AUD INT,
    result_cost_local_HKD INT,
    result_cost_nomad_HKD INT,
    result_cost_expat_HKD INT,
    result_cost_longTerm_HKD INT,
    result_cost_shortTerm_HKD INT,
    result_cost_hotel_HKD INT,
    result_cost_airbnb_median_HKD INT,
    result_cost_non_alcoholic_drink_in_cafe_HKD NUMERIC(3, 2),
    result_cost_beer_in_cafe_HKD INT,
    result_cost_coffee_in_cafe_HKD NUMERIC(4, 2),
    result_cost_coworking_monthly_HKD INT,
    result_cost_local_ARS INT,
    result_cost_nomad_ARS INT,
    result_cost_expat_ARS INT,
    result_cost_longTerm_ARS INT,
    result_cost_shortTerm_ARS INT,
    result_cost_hotel_ARS INT,
    result_cost_airbnb_median_ARS INT,
    result_cost_non_alcoholic_drink_in_cafe_ARS NUMERIC(4, 2),
    result_cost_beer_in_cafe_ARS NUMERIC(4, 2),
    result_cost_coffee_in_cafe_ARS NUMERIC(4, 2),
    result_cost_coworking_monthly_ARS NUMERIC(6, 2),
    result_cost_local_BRL INT,
    result_cost_nomad_BRL INT,
    result_cost_expat_BRL INT,
    result_cost_longTerm_BRL INT,
    result_cost_shortTerm_BRL INT,
    result_cost_hotel_BRL INT,
    result_cost_airbnb_median_BRL INT,
    result_cost_non_alcoholic_drink_in_cafe_BRL NUMERIC(12, 11),
    result_cost_beer_in_cafe_BRL NUMERIC(4, 2),
    result_cost_coffee_in_cafe_BRL NUMERIC(3, 2),
    result_cost_coworking_monthly_BRL NUMERIC(5, 2),
    result_cost_local_KRW INT,
    result_cost_nomad_KRW INT,
    result_cost_expat_KRW INT,
    result_cost_longTerm_KRW INT,
    result_cost_shortTerm_KRW INT,
    result_cost_hotel_KRW INT,
    result_cost_airbnb_median_KRW INT,
    result_cost_non_alcoholic_drink_in_cafe_KRW NUMERIC(6, 2),
    result_cost_beer_in_cafe_KRW NUMERIC(6, 2),
    result_cost_coffee_in_cafe_KRW NUMERIC(6, 2),
    result_cost_coworking_monthly_KRW INT,
    result_cost_local_ILS INT,
    result_cost_nomad_ILS INT,
    result_cost_expat_ILS INT,
    result_cost_longTerm_ILS INT,
    result_cost_shortTerm_ILS INT,
    result_cost_hotel_ILS INT,
    result_cost_airbnb_median_ILS INT,
    result_cost_non_alcoholic_drink_in_cafe_ILS NUMERIC(4, 2),
    result_cost_beer_in_cafe_ILS NUMERIC(3, 1),
    result_cost_coffee_in_cafe_ILS NUMERIC(4, 2),
    result_cost_coworking_monthly_ILS NUMERIC(6, 2),
    result_cost_local_CHF INT,
    result_cost_nomad_CHF INT,
    result_cost_expat_CHF INT,
    result_cost_longTerm_CHF INT,
    result_cost_shortTerm_CHF INT,
    result_cost_hotel_CHF INT,
    result_cost_airbnb_median_CHF INT,
    result_cost_non_alcoholic_drink_in_cafe_CHF NUMERIC(3, 2),
    result_cost_beer_in_cafe_CHF NUMERIC(4, 2),
    result_cost_coffee_in_cafe_CHF NUMERIC(3, 2),
    result_cost_coworking_monthly_CHF NUMERIC(6, 2),
    result_cost_local_CAD INT,
    result_cost_nomad_CAD INT,
    result_cost_expat_CAD INT,
    result_cost_longTerm_CAD INT,
    result_cost_shortTerm_CAD INT,
    result_cost_hotel_CAD INT,
    result_cost_airbnb_median_CAD INT,
    result_cost_non_alcoholic_drink_in_cafe_CAD NUMERIC(3, 2),
    result_cost_beer_in_cafe_CAD NUMERIC(4, 2),
    result_cost_coffee_in_cafe_CAD NUMERIC(3, 2),
    result_cost_coworking_monthly_CAD NUMERIC(5, 2),
    result_cost_local_PAB INT,
    result_cost_nomad_PAB INT,
    result_cost_expat_PAB INT,
    result_cost_longTerm_PAB INT,
    result_cost_shortTerm_PAB INT,
    result_cost_hotel_PAB INT,
    result_cost_airbnb_median_PAB INT,
    result_cost_non_alcoholic_drink_in_cafe_PAB NUMERIC(2, 1),
    result_cost_beer_in_cafe_PAB NUMERIC(2, 1),
    result_cost_coffee_in_cafe_PAB NUMERIC(3, 2),
    result_cost_coworking_monthly_PAB INT,
    result_cost_local_SGD INT,
    result_cost_nomad_SGD INT,
    result_cost_expat_SGD INT,
    result_cost_longTerm_SGD INT,
    result_cost_shortTerm_SGD INT,
    result_cost_hotel_SGD INT,
    result_cost_airbnb_median_SGD INT,
    result_cost_non_alcoholic_drink_in_cafe_SGD NUMERIC(3, 2),
    result_cost_beer_in_cafe_SGD NUMERIC(12, 11),
    result_cost_coffee_in_cafe_SGD NUMERIC(3, 2),
    result_cost_coworking_monthly_SGD INT,
    result_cost_local_MXN INT,
    result_cost_nomad_MXN INT,
    result_cost_expat_MXN INT,
    result_cost_longTerm_MXN INT,
    result_cost_shortTerm_MXN INT,
    result_cost_hotel_MXN INT,
    result_cost_airbnb_median_MXN INT,
    result_cost_non_alcoholic_drink_in_cafe_MXN NUMERIC(4, 2),
    result_cost_beer_in_cafe_MXN NUMERIC(4, 2),
    result_cost_coffee_in_cafe_MXN NUMERIC(4, 2),
    result_cost_coworking_monthly_MXN NUMERIC(7, 2),
    result_cost_local_RON INT,
    result_cost_nomad_RON INT,
    result_cost_expat_RON INT,
    result_cost_longTerm_RON INT,
    result_cost_shortTerm_RON INT,
    result_cost_hotel_RON INT,
    result_cost_airbnb_median_RON INT,
    result_cost_non_alcoholic_drink_in_cafe_RON NUMERIC(3, 2),
    result_cost_beer_in_cafe_RON NUMERIC(3, 1),
    result_cost_coffee_in_cafe_RON NUMERIC(3, 2),
    result_cost_coworking_monthly_RON NUMERIC(5, 2),
    result_cost_local_JPY INT,
    result_cost_nomad_JPY INT,
    result_cost_expat_JPY INT,
    result_cost_longTerm_JPY INT,
    result_cost_shortTerm_JPY INT,
    result_cost_hotel_JPY INT,
    result_cost_airbnb_median_JPY INT,
    result_cost_non_alcoholic_drink_in_cafe_JPY NUMERIC(5, 2),
    result_cost_beer_in_cafe_JPY NUMERIC(5, 2),
    result_cost_coffee_in_cafe_JPY NUMERIC(5, 2),
    result_cost_coworking_monthly_JPY INT,
    result_cost_local_PLN INT,
    result_cost_nomad_PLN INT,
    result_cost_expat_PLN INT,
    result_cost_longTerm_PLN INT,
    result_cost_shortTerm_PLN INT,
    result_cost_hotel_PLN INT,
    result_cost_airbnb_median_PLN INT,
    result_cost_non_alcoholic_drink_in_cafe_PLN NUMERIC(3, 2),
    result_cost_beer_in_cafe_PLN NUMERIC(3, 1),
    result_cost_coffee_in_cafe_PLN NUMERIC(3, 2),
    result_cost_coworking_monthly_PLN NUMERIC(5, 2),
    result_cost_local_MOP INT,
    result_cost_nomad_MOP INT,
    result_cost_expat_MOP INT,
    result_cost_longTerm_MOP INT,
    result_cost_shortTerm_MOP INT,
    result_cost_hotel_MOP INT,
    result_cost_airbnb_median_MOP INT,
    result_cost_non_alcoholic_drink_in_cafe_MOP NUMERIC(3, 2),
    result_cost_beer_in_cafe_MOP NUMERIC(3, 1),
    result_cost_coffee_in_cafe_MOP NUMERIC(4, 2),
    result_cost_coworking_monthly_MOP INT,
    result_cost_local_GBP INT,
    result_cost_nomad_GBP INT,
    result_cost_expat_GBP INT,
    result_cost_longTerm_GBP INT,
    result_cost_shortTerm_GBP INT,
    result_cost_hotel_GBP INT,
    result_cost_airbnb_median_GBP INT,
    result_cost_non_alcoholic_drink_in_cafe_GBP NUMERIC(3, 2),
    result_cost_beer_in_cafe_GBP NUMERIC(4, 2),
    result_cost_coffee_in_cafe_GBP NUMERIC(3, 2),
    result_cost_coworking_monthly_GBP NUMERIC(5, 2),
    result_cost_local_INR INT,
    result_cost_nomad_INR INT,
    result_cost_expat_INR INT,
    result_cost_longTerm_INR INT,
    result_cost_shortTerm_INR INT,
    result_cost_hotel_INR INT,
    result_cost_airbnb_median_INR INT,
    result_cost_non_alcoholic_drink_in_cafe_INR NUMERIC(4, 2),
    result_cost_beer_in_cafe_INR NUMERIC(5, 2),
    result_cost_coffee_in_cafe_INR NUMERIC(5, 2),
    result_cost_coworking_monthly_INR NUMERIC(7, 2),
    result_cost_local_UYU INT,
    result_cost_nomad_UYU INT,
    result_cost_expat_UYU INT,
    result_cost_longTerm_UYU INT,
    result_cost_shortTerm_UYU INT,
    result_cost_hotel_UYU INT,
    result_cost_airbnb_median_UYU INT,
    result_cost_non_alcoholic_drink_in_cafe_UYU NUMERIC(3, 1),
    result_cost_beer_in_cafe_UYU INT,
    result_cost_coffee_in_cafe_UYU INT,
    result_cost_coworking_monthly_UYU INT,
    result_cost_local_CNY INT,
    result_cost_nomad_CNY INT,
    result_cost_expat_CNY INT,
    result_cost_longTerm_CNY INT,
    result_cost_shortTerm_CNY INT,
    result_cost_hotel_CNY INT,
    result_cost_airbnb_median_CNY INT,
    result_cost_non_alcoholic_drink_in_cafe_CNY NUMERIC(3, 2),
    result_cost_beer_in_cafe_CNY NUMERIC(4, 2),
    result_cost_coffee_in_cafe_CNY NUMERIC(4, 2),
    result_cost_coworking_monthly_CNY NUMERIC(6, 2),
    result_cost_local_MKD INT,
    result_cost_nomad_MKD INT,
    result_cost_expat_MKD INT,
    result_cost_longTerm_MKD INT,
    result_cost_shortTerm_MKD INT,
    result_cost_hotel_MKD INT,
    result_cost_airbnb_median_MKD INT,
    result_cost_non_alcoholic_drink_in_cafe_MKD NUMERIC(4, 2),
    result_cost_beer_in_cafe_MKD INT,
    result_cost_coffee_in_cafe_MKD NUMERIC(4, 2),
    result_cost_coworking_monthly_MKD NUMERIC(6, 2),
    result_cost_local_CLP INT,
    result_cost_nomad_CLP INT,
    result_cost_expat_CLP INT,
    result_cost_longTerm_CLP INT,
    result_cost_shortTerm_CLP INT,
    result_cost_hotel_CLP INT,
    result_cost_airbnb_median_CLP INT,
    result_cost_non_alcoholic_drink_in_cafe_CLP NUMERIC(5, 2),
    result_cost_beer_in_cafe_CLP INT,
    result_cost_coffee_in_cafe_CLP NUMERIC(5, 2),
    result_cost_coworking_monthly_CLP INT,
    result_cost_local_NOK INT,
    result_cost_nomad_NOK INT,
    result_cost_expat_NOK INT,
    result_cost_longTerm_NOK INT,
    result_cost_shortTerm_NOK INT,
    result_cost_hotel_NOK INT,
    result_cost_airbnb_median_NOK INT,
    result_cost_non_alcoholic_drink_in_cafe_NOK NUMERIC(4, 2),
    result_cost_beer_in_cafe_NOK INT,
    result_cost_coffee_in_cafe_NOK NUMERIC(4, 2),
    result_cost_coworking_monthly_NOK NUMERIC(6, 2),
    result_cost_local_RSD INT,
    result_cost_nomad_RSD INT,
    result_cost_expat_RSD INT,
    result_cost_longTerm_RSD INT,
    result_cost_shortTerm_RSD INT,
    result_cost_hotel_RSD INT,
    result_cost_airbnb_median_RSD INT,
    result_cost_non_alcoholic_drink_in_cafe_RSD NUMERIC(4, 2),
    result_cost_beer_in_cafe_RSD NUMERIC(12, 9),
    result_cost_coffee_in_cafe_RSD NUMERIC(5, 2),
    result_cost_coworking_monthly_RSD NUMERIC(7, 2),
    result_cost_local_UAH INT,
    result_cost_nomad_UAH INT,
    result_cost_expat_UAH INT,
    result_cost_longTerm_UAH INT,
    result_cost_shortTerm_UAH INT,
    result_cost_hotel_UAH INT,
    result_cost_airbnb_median_UAH INT,
    result_cost_non_alcoholic_drink_in_cafe_UAH NUMERIC(4, 2),
    result_cost_beer_in_cafe_UAH NUMERIC(3, 1),
    result_cost_coffee_in_cafe_UAH NUMERIC(4, 2),
    result_cost_coworking_monthly_UAH INT,
    result_cost_local_HRK INT,
    result_cost_nomad_HRK INT,
    result_cost_expat_HRK INT,
    result_cost_longTerm_HRK INT,
    result_cost_shortTerm_HRK INT,
    result_cost_hotel_HRK INT,
    result_cost_airbnb_median_HRK INT,
    result_cost_non_alcoholic_drink_in_cafe_HRK NUMERIC(4, 2),
    result_cost_beer_in_cafe_HRK NUMERIC(4, 2),
    result_cost_coffee_in_cafe_HRK NUMERIC(4, 2),
    result_cost_coworking_monthly_HRK NUMERIC(6, 2),
    result_cost_local_BYR INT,
    result_cost_nomad_BYR INT,
    result_cost_expat_BYR INT,
    result_cost_longTerm_BYR INT,
    result_cost_shortTerm_BYR INT,
    result_cost_hotel_BYR INT,
    result_cost_airbnb_median_BYR INT,
    result_cost_non_alcoholic_drink_in_cafe_BYR INT,
    result_cost_beer_in_cafe_BYR INT,
    result_cost_coffee_in_cafe_BYR INT,
    result_cost_coworking_monthly_BYR INT,
    result_cost_local_TRY INT,
    result_cost_nomad_TRY INT,
    result_cost_expat_TRY INT,
    result_cost_longTerm_TRY INT,
    result_cost_shortTerm_TRY INT,
    result_cost_hotel_TRY INT,
    result_cost_airbnb_median_TRY INT,
    result_cost_non_alcoholic_drink_in_cafe_TRY NUMERIC(3, 2),
    result_cost_beer_in_cafe_TRY NUMERIC(3, 2),
    result_cost_coffee_in_cafe_TRY NUMERIC(12, 11),
    result_cost_coworking_monthly_TRY NUMERIC(6, 2),
    result_cost_local_CRC INT,
    result_cost_nomad_CRC INT,
    result_cost_expat_CRC INT,
    result_cost_longTerm_CRC INT,
    result_cost_shortTerm_CRC INT,
    result_cost_hotel_CRC INT,
    result_cost_airbnb_median_CRC INT,
    result_cost_non_alcoholic_drink_in_cafe_CRC INT,
    result_cost_beer_in_cafe_CRC INT,
    result_cost_coffee_in_cafe_CRC INT,
    result_cost_coworking_monthly_CRC INT,
    result_cost_local_DKK INT,
    result_cost_nomad_DKK INT,
    result_cost_expat_DKK INT,
    result_cost_longTerm_DKK INT,
    result_cost_shortTerm_DKK INT,
    result_cost_hotel_DKK INT,
    result_cost_airbnb_median_DKK INT,
    result_cost_non_alcoholic_drink_in_cafe_DKK NUMERIC(4, 2),
    result_cost_beer_in_cafe_DKK INT,
    result_cost_coffee_in_cafe_DKK NUMERIC(4, 2),
    result_cost_coworking_monthly_DKK NUMERIC(6, 2),
    result_cost_local_MYR INT,
    result_cost_nomad_MYR INT,
    result_cost_expat_MYR INT,
    result_cost_longTerm_MYR INT,
    result_cost_shortTerm_MYR INT,
    result_cost_hotel_MYR INT,
    result_cost_airbnb_median_MYR INT,
    result_cost_non_alcoholic_drink_in_cafe_MYR NUMERIC(3, 2),
    result_cost_beer_in_cafe_MYR NUMERIC(4, 2),
    result_cost_coffee_in_cafe_MYR NUMERIC(4, 2),
    result_cost_coworking_monthly_MYR NUMERIC(7, 3),
    result_cost_local_GIP INT,
    result_cost_nomad_GIP INT,
    result_cost_expat_GIP INT,
    result_cost_longTerm_GIP INT,
    result_cost_shortTerm_GIP INT,
    result_cost_hotel_GIP INT,
    result_cost_airbnb_median_GIP INT,
    result_cost_non_alcoholic_drink_in_cafe_GIP NUMERIC(3, 2),
    result_cost_beer_in_cafe_GIP INT,
    result_cost_coffee_in_cafe_GIP NUMERIC(3, 2),
    result_cost_coworking_monthly_GIP INT,
    result_cost_local_BGN INT,
    result_cost_nomad_BGN INT,
    result_cost_expat_BGN INT,
    result_cost_longTerm_BGN INT,
    result_cost_shortTerm_BGN INT,
    result_cost_hotel_BGN INT,
    result_cost_airbnb_median_BGN INT,
    result_cost_non_alcoholic_drink_in_cafe_BGN NUMERIC(3, 2),
    result_cost_beer_in_cafe_BGN NUMERIC(3, 2),
    result_cost_coffee_in_cafe_BGN NUMERIC(3, 2),
    result_cost_coworking_monthly_BGN INT,
    result_cost_local_RUB INT,
    result_cost_nomad_RUB INT,
    result_cost_expat_RUB INT,
    result_cost_longTerm_RUB INT,
    result_cost_shortTerm_RUB INT,
    result_cost_hotel_RUB INT,
    result_cost_airbnb_median_RUB INT,
    result_cost_non_alcoholic_drink_in_cafe_RUB NUMERIC(5, 2),
    result_cost_beer_in_cafe_RUB NUMERIC(5, 2),
    result_cost_coffee_in_cafe_RUB NUMERIC(5, 2),
    result_cost_coworking_monthly_RUB NUMERIC(7, 2),
    result_cost_local_DOP INT,
    result_cost_nomad_DOP INT,
    result_cost_expat_DOP INT,
    result_cost_longTerm_DOP INT,
    result_cost_shortTerm_DOP INT,
    result_cost_hotel_DOP INT,
    result_cost_airbnb_median_DOP INT,
    result_cost_non_alcoholic_drink_in_cafe_DOP NUMERIC(4, 2),
    result_cost_beer_in_cafe_DOP INT,
    result_cost_coffee_in_cafe_DOP NUMERIC(5, 2),
    result_cost_coworking_monthly_DOP INT,
    result_cost_local_JMD INT,
    result_cost_nomad_JMD INT,
    result_cost_expat_JMD INT,
    result_cost_longTerm_JMD INT,
    result_cost_shortTerm_JMD INT,
    result_cost_hotel_JMD INT,
    result_cost_airbnb_median_JMD INT,
    result_cost_non_alcoholic_drink_in_cafe_JMD INT,
    result_cost_beer_in_cafe_JMD INT,
    result_cost_coffee_in_cafe_JMD INT,
    result_cost_coworking_monthly_JMD INT,
    result_cost_local_BAM INT,
    result_cost_nomad_BAM INT,
    result_cost_expat_BAM INT,
    result_cost_longTerm_BAM INT,
    result_cost_shortTerm_BAM INT,
    result_cost_hotel_BAM INT,
    result_cost_airbnb_median_BAM INT,
    result_cost_non_alcoholic_drink_in_cafe_BAM NUMERIC(3, 2),
    result_cost_beer_in_cafe_BAM NUMERIC(2, 1),
    result_cost_coffee_in_cafe_BAM NUMERIC(3, 2),
    result_cost_coworking_monthly_BAM INT,
    result_cost_local_AED INT,
    result_cost_nomad_AED INT,
    result_cost_expat_AED INT,
    result_cost_longTerm_AED INT,
    result_cost_shortTerm_AED INT,
    result_cost_hotel_AED INT,
    result_cost_airbnb_median_AED INT,
    result_cost_non_alcoholic_drink_in_cafe_AED NUMERIC(3, 2),
    result_cost_beer_in_cafe_AED NUMERIC(3, 1),
    result_cost_coffee_in_cafe_AED NUMERIC(4, 2),
    result_cost_coworking_monthly_AED NUMERIC(6, 2),
    result_cost_local_JOD INT,
    result_cost_nomad_JOD INT,
    result_cost_expat_JOD INT,
    result_cost_longTerm_JOD INT,
    result_cost_shortTerm_JOD INT,
    result_cost_hotel_JOD INT,
    result_cost_airbnb_median_JOD INT,
    result_cost_non_alcoholic_drink_in_cafe_JOD NUMERIC(2, 1),
    result_cost_beer_in_cafe_JOD NUMERIC(2, 1),
    result_cost_coffee_in_cafe_JOD INT,
    result_cost_coworking_monthly_JOD INT,
    result_cost_local_BND INT,
    result_cost_nomad_BND INT,
    result_cost_expat_BND INT,
    result_cost_longTerm_BND INT,
    result_cost_shortTerm_BND INT,
    result_cost_hotel_BND INT,
    result_cost_airbnb_median_BND INT,
    result_cost_non_alcoholic_drink_in_cafe_BND NUMERIC(3, 2),
    result_cost_beer_in_cafe_BND INT,
    result_cost_coffee_in_cafe_BND NUMERIC(3, 2),
    result_cost_coworking_monthly_BND INT,
    result_cost_local_OMR INT,
    result_cost_nomad_OMR INT,
    result_cost_expat_OMR INT,
    result_cost_longTerm_OMR INT,
    result_cost_shortTerm_OMR INT,
    result_cost_hotel_OMR INT,
    result_cost_airbnb_median_OMR INT,
    result_cost_non_alcoholic_drink_in_cafe_OMR NUMERIC(3, 2),
    result_cost_beer_in_cafe_OMR INT,
    result_cost_coffee_in_cafe_OMR NUMERIC(3, 2),
    result_cost_coworking_monthly_OMR INT,
    result_cost_local_AMD INT,
    result_cost_nomad_AMD INT,
    result_cost_expat_AMD INT,
    result_cost_longTerm_AMD INT,
    result_cost_shortTerm_AMD INT,
    result_cost_hotel_AMD INT,
    result_cost_airbnb_median_AMD INT,
    result_cost_non_alcoholic_drink_in_cafe_AMD NUMERIC(5, 2),
    result_cost_beer_in_cafe_AMD INT,
    result_cost_coffee_in_cafe_AMD NUMERIC(5, 2),
    result_cost_coworking_monthly_AMD NUMERIC(7, 2),
    result_cost_local_PEN INT,
    result_cost_nomad_PEN INT,
    result_cost_expat_PEN INT,
    result_cost_longTerm_PEN INT,
    result_cost_shortTerm_PEN INT,
    result_cost_hotel_PEN INT,
    result_cost_airbnb_median_PEN INT,
    result_cost_non_alcoholic_drink_in_cafe_PEN NUMERIC(3, 2),
    result_cost_beer_in_cafe_PEN INT,
    result_cost_coffee_in_cafe_PEN NUMERIC(3, 2),
    result_cost_coworking_monthly_PEN NUMERIC(5, 2),
    result_cost_local_CUC INT,
    result_cost_nomad_CUC INT,
    result_cost_expat_CUC INT,
    result_cost_longTerm_CUC INT,
    result_cost_shortTerm_CUC INT,
    result_cost_hotel_CUC INT,
    result_cost_airbnb_median_CUC INT,
    result_cost_non_alcoholic_drink_in_cafe_CUC NUMERIC(2, 1),
    result_cost_beer_in_cafe_CUC INT,
    result_cost_coffee_in_cafe_CUC NUMERIC(2, 1),
    result_cost_coworking_monthly_CUC INT,
    result_cost_local_LKR INT,
    result_cost_nomad_LKR INT,
    result_cost_expat_LKR INT,
    result_cost_longTerm_LKR INT,
    result_cost_shortTerm_LKR INT,
    result_cost_hotel_LKR INT,
    result_cost_airbnb_median_LKR INT,
    result_cost_non_alcoholic_drink_in_cafe_LKR NUMERIC(5, 2),
    result_cost_beer_in_cafe_LKR INT,
    result_cost_coffee_in_cafe_LKR NUMERIC(5, 2),
    result_cost_coworking_monthly_LKR NUMERIC(7, 2),
    result_cost_local_COP INT,
    result_cost_nomad_COP INT,
    result_cost_expat_COP INT,
    result_cost_longTerm_COP INT,
    result_cost_shortTerm_COP INT,
    result_cost_hotel_COP INT,
    result_cost_airbnb_median_COP INT,
    result_cost_non_alcoholic_drink_in_cafe_COP NUMERIC(6, 2),
    result_cost_beer_in_cafe_COP NUMERIC(6, 2),
    result_cost_coffee_in_cafe_COP NUMERIC(6, 2),
    result_cost_coworking_monthly_COP INT,
    result_cost_local_XOF INT,
    result_cost_nomad_XOF INT,
    result_cost_expat_XOF INT,
    result_cost_longTerm_XOF INT,
    result_cost_shortTerm_XOF INT,
    result_cost_hotel_XOF INT,
    result_cost_airbnb_median_XOF INT,
    result_cost_non_alcoholic_drink_in_cafe_XOF NUMERIC(5, 2),
    result_cost_beer_in_cafe_XOF INT,
    result_cost_coffee_in_cafe_XOF NUMERIC(6, 2),
    result_cost_coworking_monthly_XOF NUMERIC(8, 2),
    result_cost_local_SAR INT,
    result_cost_nomad_SAR INT,
    result_cost_expat_SAR INT,
    result_cost_longTerm_SAR INT,
    result_cost_shortTerm_SAR INT,
    result_cost_hotel_SAR INT,
    result_cost_airbnb_median_SAR INT,
    result_cost_non_alcoholic_drink_in_cafe_SAR NUMERIC(3, 2),
    result_cost_beer_in_cafe_SAR NUMERIC(3, 1),
    result_cost_coffee_in_cafe_SAR NUMERIC(4, 2),
    result_cost_coworking_monthly_SAR NUMERIC(6, 2),
    result_cost_local_MUR INT,
    result_cost_nomad_MUR INT,
    result_cost_expat_MUR INT,
    result_cost_longTerm_MUR INT,
    result_cost_shortTerm_MUR INT,
    result_cost_hotel_MUR INT,
    result_cost_airbnb_median_MUR INT,
    result_cost_non_alcoholic_drink_in_cafe_MUR NUMERIC(4, 2),
    result_cost_beer_in_cafe_MUR INT,
    result_cost_coffee_in_cafe_MUR INT,
    result_cost_coworking_monthly_MUR INT,
    result_cost_local_PHP INT,
    result_cost_nomad_PHP INT,
    result_cost_expat_PHP INT,
    result_cost_longTerm_PHP INT,
    result_cost_shortTerm_PHP INT,
    result_cost_hotel_PHP INT,
    result_cost_airbnb_median_PHP INT,
    result_cost_non_alcoholic_drink_in_cafe_PHP NUMERIC(5, 2),
    result_cost_beer_in_cafe_PHP NUMERIC(4, 1),
    result_cost_coffee_in_cafe_PHP NUMERIC(5, 2),
    result_cost_coworking_monthly_PHP NUMERIC(7, 2),
    result_cost_local_GEL INT,
    result_cost_nomad_GEL INT,
    result_cost_expat_GEL INT,
    result_cost_longTerm_GEL INT,
    result_cost_shortTerm_GEL INT,
    result_cost_hotel_GEL INT,
    result_cost_airbnb_median_GEL INT,
    result_cost_non_alcoholic_drink_in_cafe_GEL NUMERIC(3, 2),
    result_cost_beer_in_cafe_GEL NUMERIC(2, 1),
    result_cost_coffee_in_cafe_GEL NUMERIC(3, 2),
    result_cost_coworking_monthly_GEL INT,
    result_cost_local_ALL INT,
    result_cost_nomad_ALL INT,
    result_cost_expat_ALL INT,
    result_cost_longTerm_ALL INT,
    result_cost_shortTerm_ALL INT,
    result_cost_hotel_ALL INT,
    result_cost_airbnb_median_ALL INT,
    result_cost_non_alcoholic_drink_in_cafe_ALL INT,
    result_cost_beer_in_cafe_ALL INT,
    result_cost_coffee_in_cafe_ALL INT,
    result_cost_coworking_monthly_ALL INT,
    result_cost_local_MAD INT,
    result_cost_nomad_MAD INT,
    result_cost_expat_MAD INT,
    result_cost_longTerm_MAD INT,
    result_cost_shortTerm_MAD INT,
    result_cost_hotel_MAD INT,
    result_cost_airbnb_median_MAD INT,
    result_cost_non_alcoholic_drink_in_cafe_MAD NUMERIC(4, 2),
    result_cost_beer_in_cafe_MAD NUMERIC(4, 2),
    result_cost_coffee_in_cafe_MAD NUMERIC(4, 2),
    result_cost_coworking_monthly_MAD NUMERIC(7, 2),
    result_cost_local_PYG INT,
    result_cost_nomad_PYG INT,
    result_cost_expat_PYG INT,
    result_cost_longTerm_PYG INT,
    result_cost_shortTerm_PYG INT,
    result_cost_hotel_PYG INT,
    result_cost_airbnb_median_PYG INT,
    result_cost_non_alcoholic_drink_in_cafe_PYG NUMERIC(6, 2),
    result_cost_beer_in_cafe_PYG NUMERIC(7, 2),
    result_cost_coffee_in_cafe_PYG NUMERIC(7, 2),
    result_cost_coworking_monthly_PYG NUMERIC(9, 2),
    result_cost_local_BHD INT,
    result_cost_nomad_BHD INT,
    result_cost_expat_BHD INT,
    result_cost_longTerm_BHD INT,
    result_cost_shortTerm_BHD INT,
    result_cost_hotel_BHD INT,
    result_cost_airbnb_median_BHD INT,
    result_cost_non_alcoholic_drink_in_cafe_BHD NUMERIC(3, 2),
    result_cost_beer_in_cafe_BHD INT,
    result_cost_coffee_in_cafe_BHD NUMERIC(3, 2),
    result_cost_coworking_monthly_BHD NUMERIC(4, 2),
    result_cost_local_QAR INT,
    result_cost_nomad_QAR INT,
    result_cost_expat_QAR INT,
    result_cost_longTerm_QAR INT,
    result_cost_shortTerm_QAR INT,
    result_cost_hotel_QAR INT,
    result_cost_airbnb_median_QAR INT,
    result_cost_non_alcoholic_drink_in_cafe_QAR INT,
    result_cost_beer_in_cafe_QAR INT,
    result_cost_coffee_in_cafe_QAR INT,
    result_cost_coworking_monthly_QAR INT,
    result_cost_local_MVR INT,
    result_cost_nomad_MVR INT,
    result_cost_expat_MVR INT,
    result_cost_longTerm_MVR INT,
    result_cost_shortTerm_MVR INT,
    result_cost_hotel_MVR INT,
    result_cost_airbnb_median_MVR INT,
    result_cost_non_alcoholic_drink_in_cafe_MVR NUMERIC(3, 2),
    result_cost_beer_in_cafe_MVR NUMERIC(3, 1),
    result_cost_coffee_in_cafe_MVR NUMERIC(4, 2),
    result_cost_coworking_monthly_MVR NUMERIC(6, 2),
    result_cost_local_BZD INT,
    result_cost_nomad_BZD INT,
    result_cost_expat_BZD INT,
    result_cost_longTerm_BZD INT,
    result_cost_shortTerm_BZD INT,
    result_cost_hotel_BZD INT,
    result_cost_airbnb_median_BZD INT,
    result_cost_non_alcoholic_drink_in_cafe_BZD NUMERIC(3, 2),
    result_cost_beer_in_cafe_BZD INT,
    result_cost_coffee_in_cafe_BZD NUMERIC(3, 2),
    result_cost_coworking_monthly_BZD NUMERIC(5, 2),
    result_cost_local_BDT INT,
    result_cost_nomad_BDT INT,
    result_cost_expat_BDT INT,
    result_cost_longTerm_BDT INT,
    result_cost_shortTerm_BDT INT,
    result_cost_hotel_BDT INT,
    result_cost_airbnb_median_BDT INT,
    result_cost_non_alcoholic_drink_in_cafe_BDT NUMERIC(4, 2),
    result_cost_beer_in_cafe_BDT INT,
    result_cost_coffee_in_cafe_BDT NUMERIC(5, 2),
    result_cost_coworking_monthly_BDT INT,
    result_cost_local_ZAR INT,
    result_cost_nomad_ZAR INT,
    result_cost_expat_ZAR INT,
    result_cost_longTerm_ZAR INT,
    result_cost_shortTerm_ZAR INT,
    result_cost_hotel_ZAR INT,
    result_cost_airbnb_median_ZAR INT,
    result_cost_non_alcoholic_drink_in_cafe_ZAR NUMERIC(4, 2),
    result_cost_beer_in_cafe_ZAR INT,
    result_cost_coffee_in_cafe_ZAR NUMERIC(4, 2),
    result_cost_coworking_monthly_ZAR NUMERIC(6, 2),
    result_cost_local_KHR INT,
    result_cost_nomad_KHR INT,
    result_cost_expat_KHR INT,
    result_cost_longTerm_KHR INT,
    result_cost_shortTerm_KHR INT,
    result_cost_hotel_KHR INT,
    result_cost_airbnb_median_KHR INT,
    result_cost_non_alcoholic_drink_in_cafe_KHR NUMERIC(6, 2),
    result_cost_beer_in_cafe_KHR INT,
    result_cost_coffee_in_cafe_KHR NUMERIC(6, 2),
    result_cost_coworking_monthly_KHR INT,
    result_cost_local_MDL INT,
    result_cost_nomad_MDL INT,
    result_cost_expat_MDL INT,
    result_cost_longTerm_MDL INT,
    result_cost_shortTerm_MDL INT,
    result_cost_hotel_MDL INT,
    result_cost_airbnb_median_MDL INT,
    result_cost_non_alcoholic_drink_in_cafe_MDL INT,
    result_cost_beer_in_cafe_MDL INT,
    result_cost_coffee_in_cafe_MDL INT,
    result_cost_coworking_monthly_MDL INT,
    result_cost_local_AZN INT,
    result_cost_nomad_AZN INT,
    result_cost_expat_AZN INT,
    result_cost_longTerm_AZN INT,
    result_cost_shortTerm_AZN INT,
    result_cost_hotel_AZN INT,
    result_cost_airbnb_median_AZN INT,
    result_cost_non_alcoholic_drink_in_cafe_AZN INT,
    result_cost_beer_in_cafe_AZN INT,
    result_cost_coffee_in_cafe_AZN INT,
    result_cost_coworking_monthly_AZN INT,
    result_cost_local_ISK INT,
    result_cost_nomad_ISK INT,
    result_cost_expat_ISK INT,
    result_cost_longTerm_ISK INT,
    result_cost_shortTerm_ISK INT,
    result_cost_hotel_ISK INT,
    result_cost_airbnb_median_ISK INT,
    result_cost_non_alcoholic_drink_in_cafe_ISK INT,
    result_cost_beer_in_cafe_ISK INT,
    result_cost_coffee_in_cafe_ISK INT,
    result_cost_coworking_monthly_ISK INT,
    result_cost_local_BOB INT,
    result_cost_nomad_BOB INT,
    result_cost_expat_BOB INT,
    result_cost_longTerm_BOB INT,
    result_cost_shortTerm_BOB INT,
    result_cost_hotel_BOB INT,
    result_cost_airbnb_median_BOB INT,
    result_cost_non_alcoholic_drink_in_cafe_BOB NUMERIC(3, 2),
    result_cost_beer_in_cafe_BOB NUMERIC(3, 1),
    result_cost_coffee_in_cafe_BOB NUMERIC(3, 2),
    result_cost_coworking_monthly_BOB NUMERIC(6, 2),
    result_cost_local_LBP INT,
    result_cost_nomad_LBP INT,
    result_cost_expat_LBP INT,
    result_cost_longTerm_LBP INT,
    result_cost_shortTerm_LBP INT,
    result_cost_hotel_LBP INT,
    result_cost_airbnb_median_LBP INT,
    result_cost_non_alcoholic_drink_in_cafe_LBP INT,
    result_cost_beer_in_cafe_LBP INT,
    result_cost_coffee_in_cafe_LBP INT,
    result_cost_coworking_monthly_LBP INT,
    result_cost_local_BMD INT,
    result_cost_nomad_BMD INT,
    result_cost_expat_BMD INT,
    result_cost_longTerm_BMD INT,
    result_cost_shortTerm_BMD INT,
    result_cost_hotel_BMD INT,
    result_cost_airbnb_median_BMD INT,
    result_cost_non_alcoholic_drink_in_cafe_BMD NUMERIC(3, 2),
    result_cost_beer_in_cafe_BMD INT,
    result_cost_coffee_in_cafe_BMD NUMERIC(3, 2),
    result_cost_coworking_monthly_BMD NUMERIC(5, 2),
    result_cost_local_KES INT,
    result_cost_nomad_KES INT,
    result_cost_expat_KES INT,
    result_cost_longTerm_KES INT,
    result_cost_shortTerm_KES INT,
    result_cost_hotel_KES INT,
    result_cost_airbnb_median_KES INT,
    result_cost_non_alcoholic_drink_in_cafe_KES INT,
    result_cost_beer_in_cafe_KES INT,
    result_cost_coffee_in_cafe_KES INT,
    result_cost_coworking_monthly_KES INT,
    result_cost_local_PKR INT,
    result_cost_nomad_PKR INT,
    result_cost_expat_PKR INT,
    result_cost_longTerm_PKR INT,
    result_cost_shortTerm_PKR INT,
    result_cost_hotel_PKR INT,
    result_cost_airbnb_median_PKR INT,
    result_cost_non_alcoholic_drink_in_cafe_PKR NUMERIC(4, 2),
    result_cost_beer_in_cafe_PKR NUMERIC(5, 2),
    result_cost_coffee_in_cafe_PKR NUMERIC(5, 2),
    result_cost_coworking_monthly_PKR NUMERIC(7, 2),
    result_cost_local_EGP INT,
    result_cost_nomad_EGP INT,
    result_cost_expat_EGP INT,
    result_cost_longTerm_EGP INT,
    result_cost_shortTerm_EGP INT,
    result_cost_hotel_EGP INT,
    result_cost_airbnb_median_EGP INT,
    result_cost_non_alcoholic_drink_in_cafe_EGP NUMERIC(3, 2),
    result_cost_beer_in_cafe_EGP NUMERIC(3, 1),
    result_cost_coffee_in_cafe_EGP NUMERIC(4, 2),
    result_cost_coworking_monthly_EGP NUMERIC(6, 2),
    result_cost_local_NIO INT,
    result_cost_nomad_NIO INT,
    result_cost_expat_NIO INT,
    result_cost_longTerm_NIO INT,
    result_cost_shortTerm_NIO INT,
    result_cost_hotel_NIO INT,
    result_cost_airbnb_median_NIO INT,
    result_cost_non_alcoholic_drink_in_cafe_NIO NUMERIC(3, 1),
    result_cost_beer_in_cafe_NIO NUMERIC(4, 2),
    result_cost_coffee_in_cafe_NIO NUMERIC(4, 2),
    result_cost_coworking_monthly_NIO INT,
    result_cost_local_CDF INT,
    result_cost_nomad_CDF INT,
    result_cost_expat_CDF INT,
    result_cost_longTerm_CDF INT,
    result_cost_shortTerm_CDF INT,
    result_cost_hotel_CDF INT,
    result_cost_airbnb_median_CDF INT,
    result_cost_non_alcoholic_drink_in_cafe_CDF INT,
    result_cost_beer_in_cafe_CDF INT,
    result_cost_coffee_in_cafe_CDF INT,
    result_cost_coworking_monthly_CDF INT,
    result_cost_local_KZT INT,
    result_cost_nomad_KZT INT,
    result_cost_expat_KZT INT,
    result_cost_longTerm_KZT INT,
    result_cost_shortTerm_KZT INT,
    result_cost_hotel_KZT INT,
    result_cost_airbnb_median_KZT INT,
    result_cost_non_alcoholic_drink_in_cafe_KZT NUMERIC(5, 2),
    result_cost_beer_in_cafe_KZT INT,
    result_cost_coffee_in_cafe_KZT NUMERIC(5, 2),
    result_cost_coworking_monthly_KZT NUMERIC(7, 2),
    result_cost_local_TND INT,
    result_cost_nomad_TND INT,
    result_cost_expat_TND INT,
    result_cost_longTerm_TND INT,
    result_cost_shortTerm_TND INT,
    result_cost_hotel_TND INT,
    result_cost_airbnb_median_TND INT,
    result_cost_non_alcoholic_drink_in_cafe_TND INT,
    result_cost_beer_in_cafe_TND INT,
    result_cost_coffee_in_cafe_TND INT,
    result_cost_coworking_monthly_TND INT,
    result_cost_local_MMK INT,
    result_cost_nomad_MMK INT,
    result_cost_expat_MMK INT,
    result_cost_longTerm_MMK INT,
    result_cost_shortTerm_MMK INT,
    result_cost_hotel_MMK INT,
    result_cost_airbnb_median_MMK INT,
    result_cost_non_alcoholic_drink_in_cafe_MMK NUMERIC(5, 2),
    result_cost_beer_in_cafe_MMK INT,
    result_cost_coffee_in_cafe_MMK NUMERIC(5, 2),
    result_cost_coworking_monthly_MMK INT,
    result_cost_local_GTQ INT,
    result_cost_nomad_GTQ INT,
    result_cost_expat_GTQ INT,
    result_cost_longTerm_GTQ INT,
    result_cost_shortTerm_GTQ INT,
    result_cost_hotel_GTQ INT,
    result_cost_airbnb_median_GTQ INT,
    result_cost_non_alcoholic_drink_in_cafe_GTQ NUMERIC(3, 2),
    result_cost_beer_in_cafe_GTQ NUMERIC(3, 1),
    result_cost_coffee_in_cafe_GTQ NUMERIC(3, 2),
    result_cost_coworking_monthly_GTQ INT,
    result_cost_local_NGN INT,
    result_cost_nomad_NGN INT,
    result_cost_expat_NGN INT,
    result_cost_longTerm_NGN INT,
    result_cost_shortTerm_NGN INT,
    result_cost_hotel_NGN INT,
    result_cost_airbnb_median_NGN INT,
    result_cost_non_alcoholic_drink_in_cafe_NGN NUMERIC(5, 2),
    result_cost_beer_in_cafe_NGN NUMERIC(5, 2),
    result_cost_coffee_in_cafe_NGN NUMERIC(6, 2),
    result_cost_coworking_monthly_NGN NUMERIC(8, 2),
    result_cost_local_LAK INT,
    result_cost_nomad_LAK INT,
    result_cost_expat_LAK INT,
    result_cost_longTerm_LAK INT,
    result_cost_shortTerm_LAK INT,
    result_cost_hotel_LAK INT,
    result_cost_airbnb_median_LAK INT,
    result_cost_non_alcoholic_drink_in_cafe_LAK NUMERIC(6, 2),
    result_cost_beer_in_cafe_LAK INT,
    result_cost_coffee_in_cafe_LAK NUMERIC(6, 2),
    result_cost_coworking_monthly_LAK INT,
    result_cost_local_NAD INT,
    result_cost_nomad_NAD INT,
    result_cost_expat_NAD INT,
    result_cost_longTerm_NAD INT,
    result_cost_shortTerm_NAD INT,
    result_cost_hotel_NAD INT,
    result_cost_airbnb_median_NAD INT,
    result_cost_non_alcoholic_drink_in_cafe_NAD NUMERIC(4, 2),
    result_cost_beer_in_cafe_NAD INT,
    result_cost_coffee_in_cafe_NAD NUMERIC(4, 2),
    result_cost_coworking_monthly_NAD INT,
    result_cost_local_MZN INT,
    result_cost_nomad_MZN INT,
    result_cost_expat_MZN INT,
    result_cost_longTerm_MZN INT,
    result_cost_shortTerm_MZN INT,
    result_cost_hotel_MZN INT,
    result_cost_airbnb_median_MZN INT,
    result_cost_non_alcoholic_drink_in_cafe_MZN NUMERIC(3, 1),
    result_cost_beer_in_cafe_MZN NUMERIC(4, 1),
    result_cost_coffee_in_cafe_MZN INT,
    result_cost_coworking_monthly_MZN INT,
    result_cost_local_DZD INT,
    result_cost_nomad_DZD INT,
    result_cost_expat_DZD INT,
    result_cost_longTerm_DZD INT,
    result_cost_shortTerm_DZD INT,
    result_cost_hotel_DZD INT,
    result_cost_airbnb_median_DZD INT,
    result_cost_non_alcoholic_drink_in_cafe_DZD INT,
    result_cost_beer_in_cafe_DZD INT,
    result_cost_coffee_in_cafe_DZD INT,
    result_cost_coworking_monthly_DZD INT,
    result_cost_local_XAF INT,
    result_cost_nomad_XAF INT,
    result_cost_expat_XAF INT,
    result_cost_longTerm_XAF INT,
    result_cost_shortTerm_XAF INT,
    result_cost_hotel_XAF INT,
    result_cost_airbnb_median_XAF INT,
    result_cost_non_alcoholic_drink_in_cafe_XAF NUMERIC(5, 2),
    result_cost_beer_in_cafe_XAF NUMERIC(4, 1),
    result_cost_coffee_in_cafe_XAF NUMERIC(6, 2),
    result_cost_coworking_monthly_XAF NUMERIC(7, 1),
    result_cost_local_NPR INT,
    result_cost_nomad_NPR INT,
    result_cost_expat_NPR INT,
    result_cost_longTerm_NPR INT,
    result_cost_shortTerm_NPR INT,
    result_cost_hotel_NPR INT,
    result_cost_airbnb_median_NPR INT,
    result_cost_non_alcoholic_drink_in_cafe_NPR NUMERIC(4, 2),
    result_cost_beer_in_cafe_NPR INT,
    result_cost_coffee_in_cafe_NPR NUMERIC(4, 2),
    result_cost_coworking_monthly_NPR INT,
    result_cost_local_MGA INT,
    result_cost_nomad_MGA INT,
    result_cost_expat_MGA INT,
    result_cost_longTerm_MGA INT,
    result_cost_shortTerm_MGA INT,
    result_cost_hotel_MGA INT,
    result_cost_airbnb_median_MGA INT,
    result_cost_non_alcoholic_drink_in_cafe_MGA NUMERIC(6, 2),
    result_cost_beer_in_cafe_MGA NUMERIC(6, 2),
    result_cost_coffee_in_cafe_MGA NUMERIC(5, 1),
    result_cost_coworking_monthly_MGA NUMERIC(7, 1),
    result_cost_local_KGS INT,
    result_cost_nomad_KGS INT,
    result_cost_expat_KGS INT,
    result_cost_longTerm_KGS INT,
    result_cost_shortTerm_KGS INT,
    result_cost_hotel_KGS INT,
    result_cost_airbnb_median_KGS INT,
    result_cost_non_alcoholic_drink_in_cafe_KGS NUMERIC(4, 2),
    result_cost_beer_in_cafe_KGS INT,
    result_cost_coffee_in_cafe_KGS NUMERIC(4, 2),
    result_cost_coworking_monthly_KGS NUMERIC(6, 2),
    result_cost_local_UGX INT,
    result_cost_nomad_UGX INT,
    result_cost_expat_UGX INT,
    result_cost_longTerm_UGX INT,
    result_cost_shortTerm_UGX INT,
    result_cost_hotel_UGX INT,
    result_cost_airbnb_median_UGX INT,
    result_cost_non_alcoholic_drink_in_cafe_UGX NUMERIC(6, 2),
    result_cost_beer_in_cafe_UGX INT,
    result_cost_coffee_in_cafe_UGX NUMERIC(6, 2),
    result_cost_coworking_monthly_UGX INT,
    result_cost_local_TZS INT,
    result_cost_nomad_TZS INT,
    result_cost_expat_TZS INT,
    result_cost_longTerm_TZS INT,
    result_cost_shortTerm_TZS INT,
    result_cost_hotel_TZS INT,
    result_cost_airbnb_median_TZS INT,
    result_cost_non_alcoholic_drink_in_cafe_TZS NUMERIC(6, 2),
    result_cost_beer_in_cafe_TZS INT,
    result_cost_coffee_in_cafe_TZS NUMERIC(6, 2),
    result_cost_coworking_monthly_TZS INT,
    result_cost_local_MNT INT,
    result_cost_nomad_MNT INT,
    result_cost_expat_MNT INT,
    result_cost_longTerm_MNT INT,
    result_cost_shortTerm_MNT INT,
    result_cost_hotel_MNT INT,
    result_cost_airbnb_median_MNT INT,
    result_cost_non_alcoholic_drink_in_cafe_MNT INT,
    result_cost_beer_in_cafe_MNT INT,
    result_cost_coffee_in_cafe_MNT INT,
    result_cost_coworking_monthly_MNT INT,
    result_cost_local_HNL INT,
    result_cost_nomad_HNL INT,
    result_cost_expat_HNL INT,
    result_cost_longTerm_HNL INT,
    result_cost_shortTerm_HNL INT,
    result_cost_hotel_HNL INT,
    result_cost_airbnb_median_HNL INT,
    result_cost_non_alcoholic_drink_in_cafe_HNL NUMERIC(4, 2),
    result_cost_beer_in_cafe_HNL NUMERIC(4, 2),
    result_cost_coffee_in_cafe_HNL NUMERIC(4, 2),
    result_cost_coworking_monthly_HNL NUMERIC(6, 2),
    result_cost_local_ETB INT,
    result_cost_nomad_ETB INT,
    result_cost_expat_ETB INT,
    result_cost_longTerm_ETB INT,
    result_cost_shortTerm_ETB INT,
    result_cost_hotel_ETB INT,
    result_cost_airbnb_median_ETB INT,
    result_cost_non_alcoholic_drink_in_cafe_ETB NUMERIC(3, 2),
    result_cost_beer_in_cafe_ETB INT,
    result_cost_coffee_in_cafe_ETB NUMERIC(4, 2),
    result_cost_coworking_monthly_ETB INT,
    result_cost_local_UZS INT,
    result_cost_nomad_UZS INT,
    result_cost_expat_UZS INT,
    result_cost_longTerm_UZS INT,
    result_cost_shortTerm_UZS INT,
    result_cost_hotel_UZS INT,
    result_cost_airbnb_median_UZS INT,
    result_cost_non_alcoholic_drink_in_cafe_UZS NUMERIC(6, 2),
    result_cost_beer_in_cafe_UZS INT,
    result_cost_coffee_in_cafe_UZS NUMERIC(6, 2),
    result_cost_coworking_monthly_UZS NUMERIC(8, 2),
    result_cost_local_AOA INT,
    result_cost_nomad_AOA INT,
    result_cost_expat_AOA INT,
    result_cost_longTerm_AOA INT,
    result_cost_shortTerm_AOA INT,
    result_cost_hotel_AOA INT,
    result_cost_airbnb_median_AOA INT,
    result_cost_non_alcoholic_drink_in_cafe_AOA NUMERIC(5, 2),
    result_cost_beer_in_cafe_AOA INT,
    result_cost_coffee_in_cafe_AOA NUMERIC(5, 2),
    result_cost_coworking_monthly_AOA INT,
    result_cost_local_GNF INT,
    result_cost_nomad_GNF INT,
    result_cost_expat_GNF INT,
    result_cost_longTerm_GNF INT,
    result_cost_shortTerm_GNF INT,
    result_cost_hotel_GNF INT,
    result_cost_airbnb_median_GNF INT,
    result_cost_non_alcoholic_drink_in_cafe_GNF NUMERIC(6, 2),
    result_cost_beer_in_cafe_GNF NUMERIC(7, 2),
    result_cost_coffee_in_cafe_GNF NUMERIC(7, 2),
    result_cost_coworking_monthly_GNF INT,
    result_cost_local_TJS INT,
    result_cost_nomad_TJS INT,
    result_cost_expat_TJS INT,
    result_cost_longTerm_TJS INT,
    result_cost_shortTerm_TJS INT,
    result_cost_hotel_TJS INT,
    result_cost_airbnb_median_TJS INT,
    result_cost_non_alcoholic_drink_in_cafe_TJS NUMERIC(3, 2),
    result_cost_beer_in_cafe_TJS INT,
    result_cost_coffee_in_cafe_TJS NUMERIC(3, 2),
    result_cost_coworking_monthly_TJS NUMERIC(5, 2),
    result_cost_local_IRR INT,
    result_cost_nomad_IRR INT,
    result_cost_expat_IRR INT,
    result_cost_longTerm_IRR INT,
    result_cost_shortTerm_IRR INT,
    result_cost_hotel_IRR INT,
    result_cost_airbnb_median_IRR INT,
    result_cost_non_alcoholic_drink_in_cafe_IRR NUMERIC(7, 2),
    result_cost_beer_in_cafe_IRR INT,
    result_cost_coffee_in_cafe_IRR NUMERIC(7, 2),
    result_cost_coworking_monthly_IRR NUMERIC(9, 2),
    result_cost_local_SDG INT,
    result_cost_nomad_SDG INT,
    result_cost_expat_SDG INT,
    result_cost_longTerm_SDG INT,
    result_cost_shortTerm_SDG INT,
    result_cost_hotel_SDG INT,
    result_cost_airbnb_median_SDG INT,
    result_cost_non_alcoholic_drink_in_cafe_SDG NUMERIC(3, 2),
    result_cost_beer_in_cafe_SDG INT,
    result_cost_coffee_in_cafe_SDG NUMERIC(3, 2),
    result_cost_coworking_monthly_SDG NUMERIC(5, 2),
    result_cost_local_PGK INT,
    result_cost_nomad_PGK INT,
    result_cost_expat_PGK INT,
    result_cost_longTerm_PGK INT,
    result_cost_shortTerm_PGK INT,
    result_cost_hotel_PGK INT,
    result_cost_airbnb_median_PGK INT,
    result_cost_non_alcoholic_drink_in_cafe_PGK NUMERIC(3, 2),
    result_cost_beer_in_cafe_PGK NUMERIC(2, 1),
    result_cost_coffee_in_cafe_PGK NUMERIC(3, 2),
    result_cost_coworking_monthly_PGK NUMERIC(5, 2),
    result_cost_local_SYP INT,
    result_cost_nomad_SYP INT,
    result_cost_expat_SYP INT,
    result_cost_longTerm_SYP INT,
    result_cost_shortTerm_SYP INT,
    result_cost_hotel_SYP INT,
    result_cost_airbnb_median_SYP INT,
    result_cost_non_alcoholic_drink_in_cafe_SYP INT,
    result_cost_beer_in_cafe_SYP INT,
    result_cost_coffee_in_cafe_SYP INT,
    result_cost_coworking_monthly_SYP INT,
    result_cost_local_SLL INT,
    result_cost_nomad_SLL INT,
    result_cost_expat_SLL INT,
    result_cost_longTerm_SLL INT,
    result_cost_shortTerm_SLL INT,
    result_cost_hotel_SLL INT,
    result_cost_airbnb_median_SLL INT,
    result_cost_non_alcoholic_drink_in_cafe_SLL NUMERIC(6, 2),
    result_cost_beer_in_cafe_SLL NUMERIC(7, 2),
    result_cost_coffee_in_cafe_SLL NUMERIC(7, 2),
    result_cost_coworking_monthly_SLL NUMERIC(9, 2),
    result_cost_local_LYD INT,
    result_cost_nomad_LYD INT,
    result_cost_expat_LYD INT,
    result_cost_longTerm_LYD INT,
    result_cost_shortTerm_LYD INT,
    result_cost_hotel_LYD INT,
    result_cost_airbnb_median_LYD INT,
    result_cost_non_alcoholic_drink_in_cafe_LYD NUMERIC(3, 2),
    result_cost_beer_in_cafe_LYD NUMERIC(2, 1),
    result_cost_coffee_in_cafe_LYD NUMERIC(3, 2),
    result_cost_coworking_monthly_LYD NUMERIC(5, 2),
    result_cost_local_IQD INT,
    result_cost_nomad_IQD INT,
    result_cost_expat_IQD INT,
    result_cost_longTerm_IQD INT,
    result_cost_shortTerm_IQD INT,
    result_cost_hotel_IQD INT,
    result_cost_airbnb_median_IQD INT,
    result_cost_non_alcoholic_drink_in_cafe_IQD NUMERIC(5, 2),
    result_cost_beer_in_cafe_IQD INT,
    result_cost_coffee_in_cafe_IQD NUMERIC(7, 2),
    result_cost_coworking_monthly_IQD INT,
    endpoint_examples VARCHAR(54)
);
